[2023-08-18 21:58:48,322] {scheduler_job.py:181} INFO - Started process (PID=18) to work on /usr/local/airflow/dags/combined_dag.py
[2023-08-18 21:58:48,325] {scheduler_job.py:632} INFO - Processing file /usr/local/airflow/dags/combined_dag.py for tasks to queue
[2023-08-18 21:58:48,327] {logging_mixin.py:104} INFO - [2023-08-18 21:58:48,327] {dagbag.py:496} INFO - Filling up the DagBag from /usr/local/airflow/dags/combined_dag.py
[2023-08-18 21:58:48,449] {logging_mixin.py:104} INFO - [2023-08-18 21:58:48,445] {dagbag.py:329} ERROR - Failed to import: /usr/local/airflow/dags/combined_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/combined_dag.py", line 37, in <module>
    run_worker = DockerOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 178, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 178, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 506, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: run_worker_container). Invalid arguments were:
**kwargs: {'volumes': ['./output:/app/output']}
[2023-08-18 21:58:48,450] {scheduler_job.py:644} WARNING - No viable dags retrieved from /usr/local/airflow/dags/combined_dag.py
[2023-08-18 21:58:48,470] {scheduler_job.py:189} INFO - Processing /usr/local/airflow/dags/combined_dag.py took 0.152 seconds
[2023-08-18 21:59:18,538] {scheduler_job.py:181} INFO - Started process (PID=19) to work on /usr/local/airflow/dags/combined_dag.py
[2023-08-18 21:59:18,542] {scheduler_job.py:632} INFO - Processing file /usr/local/airflow/dags/combined_dag.py for tasks to queue
[2023-08-18 21:59:18,543] {logging_mixin.py:104} INFO - [2023-08-18 21:59:18,543] {dagbag.py:496} INFO - Filling up the DagBag from /usr/local/airflow/dags/combined_dag.py
[2023-08-18 21:59:18,616] {logging_mixin.py:104} INFO - [2023-08-18 21:59:18,614] {dagbag.py:329} ERROR - Failed to import: /usr/local/airflow/dags/combined_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/combined_dag.py", line 37, in <module>
    run_worker = DockerOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 178, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 178, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 506, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: run_worker_container). Invalid arguments were:
**kwargs: {'volumes': ['./output:/app/output']}
[2023-08-18 21:59:18,617] {scheduler_job.py:644} WARNING - No viable dags retrieved from /usr/local/airflow/dags/combined_dag.py
[2023-08-18 21:59:18,647] {scheduler_job.py:189} INFO - Processing /usr/local/airflow/dags/combined_dag.py took 0.114 seconds
[2023-08-18 21:59:49,167] {scheduler_job.py:181} INFO - Started process (PID=20) to work on /usr/local/airflow/dags/combined_dag.py
[2023-08-18 21:59:49,170] {scheduler_job.py:632} INFO - Processing file /usr/local/airflow/dags/combined_dag.py for tasks to queue
[2023-08-18 21:59:49,171] {logging_mixin.py:104} INFO - [2023-08-18 21:59:49,171] {dagbag.py:496} INFO - Filling up the DagBag from /usr/local/airflow/dags/combined_dag.py
[2023-08-18 21:59:49,229] {logging_mixin.py:104} INFO - [2023-08-18 21:59:49,227] {dagbag.py:329} ERROR - Failed to import: /usr/local/airflow/dags/combined_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/combined_dag.py", line 37, in <module>
    run_worker = DockerOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 178, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 178, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 506, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to DockerOperator (task_id: run_worker_container). Invalid arguments were:
**kwargs: {'volumes': ['./output:/app/output']}
[2023-08-18 21:59:49,230] {scheduler_job.py:644} WARNING - No viable dags retrieved from /usr/local/airflow/dags/combined_dag.py
[2023-08-18 21:59:49,260] {scheduler_job.py:189} INFO - Processing /usr/local/airflow/dags/combined_dag.py took 0.098 seconds
